use crate::fuzzer::generic_hypercall::*;

use crate::fuzzer::xen_bindings::*;
use crate::{hypercall, hypercall_arg, hypercall_struct_field};
use libafl::state::{HasMaxSize, HasRand};
use libafl_bolts::rands::Rand;
use paste::paste;
use std::mem::offset_of;

const CTRS: &'static [fn() -> GenericHypercallDef] = &[
    mk_xen_get_pm_stat_px_stat,
    mk_xen_get_pm_stat_cx_stat,
    mk_xen_pm_op_get_para,
    mk_xen_pm_op_set_para,
    mk_xen_pm_op_set_gov,
    mk_xen_pm_op_simple,
    mk_xen_pm_op_set_max_cstate,
    mk_xen_pm_op_set_cppc,
    mk_xen_sysctl_sched_op_arinc653,
    mk_xen_sysctl_sched_op_credit,
    mk_xen_sysctl_sched_op_credit2,
    mk_xen_sysctl_psr_cmt_op,
    mk_xen_sysctl_psr_alloc,
    mk_xen_sysctl_livepatch_upload,
    mk_xen_sysctl_livepatch_get,
    mk_xen_sysctl_livepatch_list,
    mk_xen_sysctl_livepatch_action,
    mk_xen_sysctl_readconsole,
    mk_xen_sysctl_tbuf_op,
    mk_xen_sysctl_physinfo,
    mk_xen_sysctl_cputopoinfo,
    mk_xen_sysctl_pcitopoinfo,
    mk_xen_sysctl_numainfo,
    mk_xen_sysctl_sched_id,
    mk_xen_sysctl_perfc_op,
    mk_xen_sysctl_getdomaininfolist,
    mk_xen_sysctl_debug_keys,
    mk_xen_sysctl_getcpuinfo,
    mk_xen_sysctl_availheap,
    mk_xen_sysctl_cpu_hotplug,
    mk_xen_sysctl_page_offline_op,
    mk_xen_sysctl_lockprof_op,
    mk_xen_sysctl_cpupool_op,
    mk_xen_sysctl_coverage_op,
    mk_xen_sysctl_cpu_levelling_caps,
    mk_xen_sysctl_cpu_featureset,
    mk_xen_sysctl_dt_overlay,
];

// Hand-written part here. Autogenerated code goes below

hypercall! {xen_get_pm_stat_px_stat, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_get_pmstat},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.get_pmstat.type_ (uint32_t) [PMSTAT_get_max_px,
                                                  PMSTAT_get_pxstat,
                                                  PMSTAT_reset_pxstat]},
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.cpuid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.u.getpx.total (uint8_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getpx.trans_pt (u64) },
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getpx.pt (pm_px_val_t) }
            }
}

hypercall! {xen_get_pm_stat_cx_stat, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_get_pmstat},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.get_pmstat.type_ (uint32_t) [PMSTAT_get_max_cx,
                                                  PMSTAT_get_cxstat,
                                                  PMSTAT_reset_cxstat]},
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.cpuid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.u.getcx.nr (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getcx.triggers (u64) },
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getcx.residencies (u64) },
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.u.getcx.nr_pc (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.get_pmstat.u.getcx.nr_cc (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getcx.pc (u64) },
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.get_pmstat.u.getcx.cc (u64) }
            }
}

hypercall! {xen_pm_op_get_para, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.pm_op.cmd (uint32_t) = GET_CPUFREQ_PARA},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.get_para.cpu_num (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.get_para.freq_num (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.get_para.gov_num (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.pm_op.u.get_para.affected_cpus (u32) },
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.pm_op.u.get_para.scaling_available_frequencies (u32) },
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.pm_op.u.get_para.scaling_available_governors }
            }
}

hypercall! {xen_pm_op_set_para, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.pm_op.cmd (uint32_t) = SET_CPUFREQ_PARA},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)},
               hypercall_struct_field!{enum xen_sysctl:u.pm_op.u.set_para.ctrl_type  (uint32_t) [SCALING_MAX_FREQ,
                                                         SCALING_MIN_FREQ,
                                                         SCALING_SETSPEED,
                                                         SAMPLING_RATE,
                                                         UP_THRESHOLD]},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_para.ctrl_value (uint32_t)}
            }
}

hypercall! {xen_pm_op_set_gov, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.pm_op.cmd (uint32_t) = SET_CPUFREQ_GOV},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)}
               // TODO: Add scaling_governor field enum
            }
}

hypercall! {xen_pm_op_simple, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.pm_op.cmd (uint32_t)  [GET_CPUFREQ_AVGFREQ,
                                                XEN_SYSCTL_pm_op_get_max_cstate,
                                                XEN_SYSCTL_pm_op_enable_turbo,
                                                XEN_SYSCTL_pm_op_disable_turbo]},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)}
            }
}

hypercall! {xen_pm_op_set_max_cstate, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.pm_op.cmd (uint32_t) = XEN_SYSCTL_pm_op_set_max_cstate},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_max_cstate (uint32_t)}
            }
}

hypercall! {xen_pm_op_set_cppc, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pm_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.pm_op.cmd (uint32_t) = SET_CPUFREQ_CPPC},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.cpuid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.set_params (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.minimum (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.maximum (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.desired (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.energy_perf (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.pm_op.u.set_cppc.activity_window (uint32_t)}
            }
}

hypercall! {xen_sysctl_sched_op_arinc653, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_scheduler_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               // It is actually uint32, but we don't expected to have more than 256 pools
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.cpupool_id (uint8_t)},
               hypercall_struct_field!{const xen_sysctl:u.scheduler_op.sched_id (uint32_t) = XEN_SCHEDULER_ARINC653},
               hypercall_struct_field!{enum xen_sysctl:u.scheduler_op.cmd (uint32_t) [XEN_SYSCTL_SCHEDOP_putinfo, XEN_SYSCTL_SCHEDOP_getinfo]},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.scheduler_op.u.sched_arinc653.schedule (xen_sysctl_arinc653_schedule_t)}
            }
}

hypercall! {xen_sysctl_sched_op_credit, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_scheduler_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               // It is actually uint32, but we don't expected to have more than 256 pools
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.cpupool_id (uint8_t)},
               hypercall_struct_field!{const xen_sysctl:u.scheduler_op.sched_id (uint32_t) = XEN_SCHEDULER_CREDIT},
               hypercall_struct_field!{enum xen_sysctl:u.scheduler_op.cmd (uint32_t) [XEN_SYSCTL_SCHEDOP_putinfo, XEN_SYSCTL_SCHEDOP_getinfo]},
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.u.sched_credit.tslice_ms (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.u.sched_credit.ratelimit_us (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.u.sched_credit.vcpu_migr_delay_us (uint32_t)}
            }
}

hypercall! {xen_sysctl_sched_op_credit2, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_scheduler_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               // It is actually uint32, but we don't expected to have more than 256 pools
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.cpupool_id (uint8_t)},
               hypercall_struct_field!{const xen_sysctl:u.scheduler_op.sched_id (uint32_t) = XEN_SCHEDULER_CREDIT2},
               hypercall_struct_field!{enum xen_sysctl:u.scheduler_op.cmd (uint32_t) [XEN_SYSCTL_SCHEDOP_putinfo, XEN_SYSCTL_SCHEDOP_getinfo]},
               hypercall_struct_field!{var xen_sysctl:u.scheduler_op.u.sched_credit2.ratelimit_us (uint32_t)}
            }
}

hypercall! {xen_sysctl_psr_cmt_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_psr_cmt_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.psr_cmt_op.cmd (uint32_t) [XEN_SYSCTL_PSR_CMT_get_total_rmid,
                                            XEN_SYSCTL_PSR_CMT_get_l3_upscaling_factor,
                                            XEN_SYSCTL_PSR_CMT_get_l3_cache_size,
                                            XEN_SYSCTL_PSR_CMT_enabled,
                                            XEN_SYSCTL_PSR_CMT_get_l3_event_mask]},
               hypercall_struct_field!{var xen_sysctl:u.psr_cmt_op.flags (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.psr_cmt_op.u.l3_cache.cpu (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.psr_cmt_op.u.l3_cache.rsvd (uint32_t)}
            }
}

hypercall! {xen_sysctl_psr_alloc, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_psr_cmt_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.psr_alloc.cmd (uint32_t) [XEN_SYSCTL_PSR_get_l3_info,
                                                   XEN_SYSCTL_PSR_get_l2_info,
                                                   XEN_SYSCTL_PSR_get_mba_info]},
               hypercall_struct_field!{var xen_sysctl:u.psr_alloc.target (uint32_t)}
            }
}

hypercall! {xen_sysctl_livepatch_upload, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_livepatch_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.livepatch.cmd (uint32_t) = XEN_SYSCTL_LIVEPATCH_UPLOAD},
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.flags (uint32_t) [0, LIVEPATCH_FLAG_FORCE, 0xFF] },
               hypercall_struct_field!{buf_with_size xen_sysctl:u.livepatch.u.upload.name.name => u.livepatch.u.upload.name.size },
               hypercall_struct_field!{buf_with_size xen_sysctl:u.livepatch.u.upload.payload => u.livepatch.u.upload.size }
            }
}

hypercall! {xen_sysctl_livepatch_get, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_livepatch_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.livepatch.cmd (uint32_t) = XEN_SYSCTL_LIVEPATCH_GET},
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.flags (uint32_t) [0, LIVEPATCH_FLAG_FORCE, 0xFF] },
               hypercall_struct_field!{buf_with_size xen_sysctl:u.livepatch.u.get.name.name => u.livepatch.u.get.name.size }
            }
}

hypercall! {xen_sysctl_livepatch_list, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_livepatch_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.livepatch.cmd (uint32_t) = XEN_SYSCTL_LIVEPATCH_LIST},
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.flags (uint32_t) [0, LIVEPATCH_FLAG_FORCE, 0xFF] },
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.u.list.idx (uint32_t) [0, 1, 2, 3, 1024] },
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.u.list.nr (uint32_t) [0, 1,  1024] },
               hypercall_struct_field!{var xen_sysctl:u.livepatch.u.list.name_total_size (uint32_t) },
               hypercall_struct_field!{var xen_sysctl:u.livepatch.u.list.metadata_total_size (uint32_t) },
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.livepatch.u.list.status (xen_livepatch_status_t) },
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.livepatch.u.list.name },
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.livepatch.u.list.len },
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.livepatch.u.list.metadata },
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.livepatch.u.list.metadata_len }
            }
}

hypercall! {xen_sysctl_livepatch_action, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_livepatch_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{const xen_sysctl:u.livepatch.cmd (uint32_t) = XEN_SYSCTL_LIVEPATCH_ACTION},
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.flags (uint32_t) [0, LIVEPATCH_FLAG_FORCE, 0xFF] },
               hypercall_struct_field!{buf_with_size xen_sysctl:u.livepatch.u.action.name.name => u.livepatch.u.action.name.size },
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.u.action.cmd (uint32_t) [0,
                                                LIVEPATCH_ACTION_UNLOAD,
                                                LIVEPATCH_ACTION_REVERT,
                                                LIVEPATCH_ACTION_APPLY,
                                                LIVEPATCH_ACTION_REPLACE] },
               hypercall_struct_field!{enum xen_sysctl:u.livepatch.u.action.flags (uint32_t) [0, LIVEPATCH_ACTION_APPLY_NODEPS, 0xFF] }
            }
}

// (Mostly) autogerated code

hypercall! {xen_sysctl_readconsole, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_readconsole},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.readconsole.clear (uint8_t)},
               hypercall_struct_field!{var xen_sysctl:u.readconsole.incremental (uint8_t)},
               hypercall_struct_field!{var xen_sysctl:u.readconsole.index (uint32_t)},
               hypercall_struct_field!{buf_with_size xen_sysctl:u.readconsole.buffer => u.readconsole.count}
            }
}

hypercall! {xen_sysctl_tbuf_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_tbuf_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.tbuf_op.cmd (uint32_t) [XEN_SYSCTL_TBUFOP_get_info,
                                                 XEN_SYSCTL_TBUFOP_set_cpu_mask,
                                                 XEN_SYSCTL_TBUFOP_set_evt_mask,
                                                 XEN_SYSCTL_TBUFOP_set_size,
                                                 XEN_SYSCTL_TBUFOP_enable,
                                                 XEN_SYSCTL_TBUFOP_disable ]},
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.tbuf_op.cpu_mask.bitmap},
               hypercall_struct_field!{var xen_sysctl:u.tbuf_op.cpu_mask.nr_bits (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.tbuf_op.evt_mask (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.tbuf_op.buffer_mfn (uint64_t)},
               hypercall_struct_field!{var xen_sysctl:u.tbuf_op.size (uint32_t)}
            }
}

hypercall! {xen_sysctl_physinfo, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_physinfo},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.threads_per_core (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.cores_per_socket (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.nr_cpus (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.max_cpu_id (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.nr_nodes (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.max_node_id (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.cpu_khz (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.capabilities (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.arch_capabilities (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.total_pages (uint64_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.free_pages (uint64_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.scrub_pages (uint64_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.outstanding_pages (uint64_t)},
               hypercall_struct_field!{var xen_sysctl:u.physinfo.max_mfn (uint64_t)}
            }
}

hypercall! {xen_sysctl_cputopoinfo, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_cputopoinfo},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.cputopoinfo.num_cpus (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.cputopoinfo.cputopo (xen_sysctl_cputopo_t)}
            }
}

hypercall! {xen_sysctl_pcitopoinfo, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_pcitopoinfo},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.pcitopoinfo.num_devs (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.pcitopoinfo.devs (physdev_pci_device_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.pcitopoinfo.nodes (u32)}
            }
}

hypercall! {xen_sysctl_numainfo, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_numainfo},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.numainfo.num_nodes (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.numainfo.meminfo (xen_sysctl_meminfo_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.numainfo.distance (u32)}
            }
}

hypercall! {xen_sysctl_sched_id, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_sched_id},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.sched_id.sched_id (uint32_t)}
            }
}

hypercall! {xen_sysctl_perfc_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_perfc_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.perfc_op.cmd (uint32_t) [0, XEN_SYSCTL_PERFCOP_reset, XEN_SYSCTL_PERFCOP_query]},
               hypercall_struct_field!{var xen_sysctl:u.perfc_op.nr_counters (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.perfc_op.nr_vals (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.perfc_op.desc (xen_sysctl_perfc_desc_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.perfc_op.val (xen_sysctl_perfc_val_t)}
            }
}

hypercall! {xen_sysctl_getdomaininfolist, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_getdomaininfolist},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.getdomaininfolist.first_domain (domid_t)},
               hypercall_struct_field!{var xen_sysctl:u.getdomaininfolist.max_domains (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.getdomaininfolist.buffer (xen_domctl_getdomaininfo_t)},
               hypercall_struct_field!{var xen_sysctl:u.getdomaininfolist.num_domains (uint32_t)}
            }
}

hypercall! {xen_sysctl_debug_keys, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_debug_keys},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_with_size xen_sysctl:u.debug_keys.keys => u.debug_keys.nr_keys}
            }
}

hypercall! {xen_sysctl_getcpuinfo, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_getcpuinfo},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.getcpuinfo.max_cpus (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.getcpuinfo.info (xen_sysctl_cpuinfo_t)},
               hypercall_struct_field!{var xen_sysctl:u.getcpuinfo.nr_cpus (uint32_t)}
            }
}

hypercall! {xen_sysctl_availheap, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_availheap},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.availheap.min_bitwidth (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.availheap.max_bitwidth (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.availheap.node (int32_t)},
               hypercall_struct_field!{var xen_sysctl:u.availheap.avail_bytes (uint64_t)}
            }
}

hypercall! {xen_sysctl_cpu_hotplug, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_cpu_hotplug},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.cpu_hotplug.cpu (uint32_t)},
               hypercall_struct_field!{enum xen_sysctl:u.cpu_hotplug.op (uint32_t) [XEN_SYSCTL_CPU_HOTPLUG_ONLINE,
                                                XEN_SYSCTL_CPU_HOTPLUG_OFFLINE,
                                                XEN_SYSCTL_CPU_HOTPLUG_SMT_ENABLE,
                                                XEN_SYSCTL_CPU_HOTPLUG_SMT_DISABLE]}
            }
}

hypercall! {xen_sysctl_page_offline_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_page_offline_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.page_offline.cmd (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.page_offline.start (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.page_offline.end (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.page_offline.status (u32)}
            }
}

hypercall! {xen_sysctl_lockprof_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_lockprof_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.lockprof_op.cmd (uint32_t)[0, XEN_SYSCTL_LOCKPROF_reset, XEN_SYSCTL_LOCKPROF_query]},
               hypercall_struct_field!{var xen_sysctl:u.lockprof_op.max_elem (uint32_t)},
               hypercall_struct_field!{enum xen_sysctl:u.lockprof_op.nr_elem (uint32_t) [0, 1, 0xFFFFFFFF]},
               hypercall_struct_field!{var xen_sysctl:u.lockprof_op.time (uint64_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.lockprof_op.data (xen_sysctl_lockprof_data_t)}
            }
}

hypercall! {xen_sysctl_cpupool_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_cpupool_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.cpupool_op.op (uint32_t) [0,
                                                   XEN_SYSCTL_CPUPOOL_OP_CREATE,
                                                   XEN_SYSCTL_CPUPOOL_OP_DESTROY,
                                                   XEN_SYSCTL_CPUPOOL_OP_INFO,
                                                   XEN_SYSCTL_CPUPOOL_OP_ADDCPU,
                                                   XEN_SYSCTL_CPUPOOL_OP_RMCPU,
                                                   XEN_SYSCTL_CPUPOOL_OP_MOVEDOMAIN,
                                                   XEN_SYSCTL_CPUPOOL_OP_FREEINFO ]},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.cpupool_id (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.sched_id (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.domid (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.cpu (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.n_dom (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_sysctl:u.cpupool_op.cpumap.bitmap},
               hypercall_struct_field!{var xen_sysctl:u.cpupool_op.cpumap.nr_bits (uint32_t)}
            }
}

hypercall! {xen_sysctl_coverage_op, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_coverage_op},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{enum xen_sysctl:u.coverage_op.cmd (uint32_t) [0,
                                                 XEN_SYSCTL_COVERAGE_get_size,
                                                 XEN_SYSCTL_COVERAGE_read,
                                                 XEN_SYSCTL_COVERAGE_reset]},
               hypercall_struct_field!{buf_with_size xen_sysctl:u.coverage_op.buffer => u.coverage_op.size}
            }
}

hypercall! {xen_sysctl_cpu_levelling_caps, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_get_cpu_levelling_caps},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.cpu_levelling_caps.caps (uint32_t)}
            }
}

hypercall! {xen_sysctl_cpu_featureset, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_get_cpu_featureset},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_sysctl:u.cpu_featureset.index (uint32_t)},
               hypercall_struct_field!{var xen_sysctl:u.cpu_featureset.nr_features (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_sysctl:u.cpu_featureset.features (u32)}
            }
}

hypercall! {xen_sysctl_dt_overlay, __HYPERVISOR_sysctl,
            hypercall_arg!{0, complex_struct xen_sysctl,
               hypercall_struct_field!{const xen_sysctl:cmd (uint32_t) = XEN_SYSCTL_dt_overlay},
               hypercall_struct_field!{const xen_sysctl:interface_version (uint32_t) = XEN_SYSCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_with_size xen_sysctl:u.dt_overlay.overlay_fdt => u.dt_overlay.overlay_fdt_size},
               hypercall_struct_field!{enum xen_sysctl:u.dt_overlay.overlay_op (uint8_t)[0,
                                                     XEN_SYSCTL_DT_OVERLAY_ADD as u8,
                                                     XEN_SYSCTL_DT_OVERLAY_REMOVE as u8
               ]}
            }
}

pub fn generate_sysctl_op<S>(state: &mut S) -> GenericHypercallInput
where
    S: HasRand + HasMaxSize,
{
    // Safety: CTRS are nonempty
    GenericHypercallInput::new(state.rand_mut().choose(CTRS).unwrap()(), state)
}
