use crate::fuzzer::generic_hypercall::*;

use crate::fuzzer::xen_bindings::*;
use crate::{hypercall, hypercall_arg, hypercall_struct_field};
use libafl::state::{HasMaxSize, HasRand};
use libafl_bolts::rands::Rand;
use paste::paste;
use std::mem::offset_of;

const CTRS: &'static [fn() -> GenericHypercallDef] = &[
    // Hand-written
    mk_xen_domctl_createdomain,
    // Generated
    mk_xen_domctl_getdomaininfo,
    mk_xen_domctl_getpageframeinfo3,
    mk_xen_domctl_getnodeaffinity,
    mk_xen_domctl_setnodeaffinity,
    mk_xen_domctl_getvcpuaffinity,
    mk_xen_domctl_setvcpuaffinity,
    mk_xen_domctl_shadow_op,
    mk_xen_domctl_max_mem,
    mk_xen_domctl_getvcpucontext,
    mk_xen_domctl_setvcpucontext,
    mk_xen_domctl_getvcpuinfo,
    mk_xen_domctl_max_vcpus,
    mk_xen_domctl_setdomainhandle,
    mk_xen_domctl_setdebugging,
    mk_xen_domctl_irq_permission,
    mk_xen_domctl_gsi_permission,
    mk_xen_domctl_iomem_permission,
    mk_xen_domctl_ioport_permission,
    mk_xen_domctl_hypercall_init,
    mk_xen_domctl_settimeoffset,
    mk_xen_domctl_gettscinfo,
    mk_xen_domctl_settscinfo,
    mk_xen_domctl_gethvmcontext,
    mk_xen_domctl_sethvmcontext,
    mk_xen_domctl_gethvmcontext_partial,
    mk_xen_domctl_get_address_size,
    mk_xen_domctl_set_address_size,
    mk_xen_domctl_sendtrigger,
    mk_xen_domctl_get_device_group,
    mk_xen_domctl_memory_mapping,
    mk_xen_domctl_ioport_mapping,
    mk_xen_domctl_get_ext_vcpucontext,
    mk_xen_domctl_set_ext_vcpucontext,
    mk_xen_domctl_set_target,
    mk_xen_domctl_subscribe,
    mk_xen_domctl_debug_op,
    mk_xen_domctl_access_required,
    mk_xen_domctl_audit_p2m,
    mk_xen_domctl_set_virq_handler,
    mk_xen_domctl_gdbsx_guest_memio,
    mk_xen_domctl_set_broken_page_p2m,
    mk_xen_domctl_cacheflush,
    mk_xen_domctl_gdbsx_pausevcpu,
    mk_xen_domctl_gdbsx_unpausevcpu,
    mk_xen_domctl_gdbsx_domstatus,
    mk_xen_domctl_setvnumainfo,
    mk_xen_domctl_psr_cmt_op,
    mk_xen_domctl_psr_alloc,
    mk_xen_domctl_vuart_op,
    mk_xen_domctl_vmtrace_op,
    mk_xen_domctl_get_paging_mempool_size,
    mk_xen_domctl_set_paging_mempool_size,
    mk_xen_domctl_dt_overlay,
    mk_xen_domctl_set_llc_colors,
    mk_xen_domctl_get_domain_state,
];

// Hand-written part. Autogenerated code goes below

hypercall! {xen_domctl_createdomain, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_createdomain},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.createdomain.ssidref (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.handle (xen_domain_handle_t)},
               // It is actually uint32_t, but only 9 bits are used right now
               hypercall_struct_field!{var xen_domctl:u.createdomain.flags (uint16_t)},
               hypercall_struct_field!{enum xen_domctl:u.createdomain.iommu_opts (uint32_t) [0,
                                                     XEN_DOMCTL_IOMMU_no_sharept,
                                                     2]},
               hypercall_struct_field!{var xen_domctl:u.createdomain.max_vcpus (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.max_evtchn_port (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.max_evtchn_port (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.max_grant_frames (int32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.max_maptrack_frames (int32_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.grant_opts (uint32_t)},
               hypercall_struct_field!{enum xen_domctl:u.createdomain.altp2m.opts (uint32_t) [0,
                                                      XEN_DOMCTL_ALTP2M_mixed,
                                                      XEN_DOMCTL_ALTP2M_external,
                                                      XEN_DOMCTL_ALTP2M_limited,
                                                      4]},
               hypercall_struct_field!{var xen_domctl:u.createdomain.altp2m.nr (uint16_t)},
               hypercall_struct_field!{var xen_domctl:u.createdomain.vmtrace_size (uint16_t)},
               // TODO: Use "interesting mutatotor"
               hypercall_struct_field!{enum xen_domctl:u.createdomain.cpupool_id (uint32_t)
                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]},
               hypercall_struct_field!{enum xen_domctl:u.createdomain.arch.gic_version (uint8_t)
                           [0, 1, 2, 3, 4, 5, 6, 7, 8]},
               hypercall_struct_field!{var xen_domctl:u.createdomain.arch.sve_vl (uint8_t)},
               hypercall_struct_field!{enum xen_domctl:u.createdomain.arch.tee_type (uint8_t)
                           [0, 1, 2, 3, 4]},
               hypercall_struct_field!{var xen_domctl:u.createdomain.arch.nr_spis (uint32_t)}
            }
}

// (Mostly) autogerated code
hypercall! {xen_domctl_getdomaininfo, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getdomaininfo},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.domain (domid_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.flags (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.tot_pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.max_pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.outstanding_pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.shr_pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.paged_pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.shared_info_frame (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.cpu_time (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.nr_online_vcpus (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.max_vcpu_id (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.ssidref (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.handle (xen_domain_handle_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.cpupool (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.gpaddr_bits (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.gic_version (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.sve_vl (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.tee_type (uint16_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.nr_spis (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.clock_frequency (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getdomaininfo.arch_config.arm_sci_type (uint8_t)}
            }
}

hypercall! {xen_domctl_getpageframeinfo3, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getpageframeinfo3},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.getpageframeinfo3.num (uint64_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.getpageframeinfo3.array (xen_pfn_t)}
            }
}

hypercall! {xen_domctl_getnodeaffinity, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getnodeaffinity},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.nodeaffinity.nodemap.bitmap},
               hypercall_struct_field!{var xen_domctl:u.nodeaffinity.nodemap.nr_bits (uint32_t)}
            }
}

hypercall! {xen_domctl_setnodeaffinity, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setnodeaffinity},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.nodeaffinity.nodemap.bitmap},
               hypercall_struct_field!{var xen_domctl:u.nodeaffinity.nodemap.nr_bits (uint32_t)}
            }
}

hypercall! {xen_domctl_getvcpuaffinity, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getvcpuaffinity},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.flags (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.vcpuaffinity.cpumap_hard.bitmap},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.cpumap_hard.nr_bits (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.vcpuaffinity.cpumap_soft.bitmap},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.cpumap_soft.nr_bits (uint32_t)}
            }
}

hypercall! {xen_domctl_setvcpuaffinity, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setvcpuaffinity},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.flags (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.vcpuaffinity.cpumap_hard.bitmap},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.cpumap_hard.nr_bits (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.vcpuaffinity.cpumap_soft.bitmap},
               hypercall_struct_field!{var xen_domctl:u.vcpuaffinity.cpumap_soft.nr_bits (uint32_t)}
            }
}

hypercall! {xen_domctl_shadow_op, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_shadow_op},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.op (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.mode (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.mb (uint32_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.shadow_op.dirty_bitmap},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.pages (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.stats.fault_count (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.shadow_op.stats.dirty_count (uint32_t)}
            }
}

hypercall! {xen_domctl_max_mem, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_max_mem},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.max_mem.max_memkb (uint64_t)}
            }
}

hypercall! {xen_domctl_getvcpucontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getvcpucontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vcpucontext.vcpu (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vcpucontext.ctxt (vcpu_guest_context_t)}
            }
}

hypercall! {xen_domctl_setvcpucontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setvcpucontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vcpucontext.vcpu (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vcpucontext.ctxt (vcpu_guest_context_t)}
            }
}

hypercall! {xen_domctl_getvcpuinfo, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_getvcpuinfo},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.online (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.blocked (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.running (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.cpu_time (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.getvcpuinfo.cpu (uint32_t)}
            }
}

hypercall! {xen_domctl_max_vcpus, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_max_vcpus},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.max_vcpus.max (uint32_t)}
            }
}

hypercall! {xen_domctl_setdomainhandle, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setdomainhandle},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.setdomainhandle.handle (xen_domain_handle_t)}
            }
}

hypercall! {xen_domctl_setdebugging, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setdebugging},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.setdebugging.enable (uint8_t)}
            }
}

hypercall! {xen_domctl_irq_permission, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_irq_permission},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.irq_permission.pirq (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.irq_permission.allow_access (uint8_t)}
            }
}

hypercall! {xen_domctl_gsi_permission, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gsi_permission},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.gsi_permission.gsi (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.gsi_permission.flags (uint32_t)}
            }
}

hypercall! {xen_domctl_iomem_permission, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_iomem_permission},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.iomem_permission.first_mfn (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.iomem_permission.nr_mfns (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.iomem_permission.allow_access (uint8_t)}
            }
}

hypercall! {xen_domctl_ioport_permission, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_ioport_permission},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.ioport_permission.first_port (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ioport_permission.nr_ports (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ioport_permission.allow_access (uint8_t)}
            }
}

hypercall! {xen_domctl_hypercall_init, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_hypercall_init},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.hypercall_init.gmfn (uint64_t)}
            }
}

hypercall! {xen_domctl_settimeoffset, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_settimeoffset},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.settimeoffset.time_offset_seconds (int64_t)}
            }
}

hypercall! {xen_domctl_gettscinfo, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gettscinfo},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.tsc_mode (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.gtsc_khz (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.incarnation (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.elapsed_nsec (uint64_t)}
            }
}

hypercall! {xen_domctl_settscinfo, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_settscinfo},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.tsc_mode (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.gtsc_khz (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.incarnation (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.tsc_info.elapsed_nsec (uint64_t)}
            }
}

hypercall! {xen_domctl_gethvmcontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gethvmcontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_with_size xen_domctl:u.hvmcontext.buffer => u.hvmcontext.size}
            }
}

hypercall! {xen_domctl_sethvmcontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_sethvmcontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_with_size xen_domctl:u.hvmcontext.buffer => u.hvmcontext.size}
            }
}

hypercall! {xen_domctl_gethvmcontext_partial, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gethvmcontext_partial},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.hvmcontext_partial.type_ (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.hvmcontext_partial.instance (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.hvmcontext_partial.bufsz (uint64_t)},
               hypercall_struct_field!{buf_wo_size xen_domctl:u.hvmcontext_partial.buffer}
            }
}

hypercall! {xen_domctl_get_address_size, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_get_address_size},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.address_size.size (uint32_t)}
            }
}

hypercall! {xen_domctl_set_address_size, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_address_size},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.address_size.size (uint32_t)}
            }
}

hypercall! {xen_domctl_sendtrigger, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_sendtrigger},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.sendtrigger.trigger (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.sendtrigger.vcpu (uint32_t)}
            }
}

hypercall! {xen_domctl_get_device_group, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_get_device_group},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.get_device_group.machine_sbdf (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.get_device_group.max_sdevs (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.get_device_group.num_sdevs (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.get_device_group.sdev_array (u32)}
            }
}

hypercall! {xen_domctl_memory_mapping, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_memory_mapping},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.memory_mapping.first_gfn (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.memory_mapping.first_mfn (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.memory_mapping.nr_mfns (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.memory_mapping.add_mapping (uint32_t)}
            }
}

hypercall! {xen_domctl_ioport_mapping, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_ioport_mapping},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.ioport_mapping.first_gport (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ioport_mapping.first_mport (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ioport_mapping.nr_ports (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ioport_mapping.add_mapping (uint32_t)}
            }
}

hypercall! {xen_domctl_get_ext_vcpucontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_get_ext_vcpucontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.ext_vcpucontext.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ext_vcpucontext.size (uint32_t)}
            }
}

hypercall! {xen_domctl_set_ext_vcpucontext, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_ext_vcpucontext},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.ext_vcpucontext.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.ext_vcpucontext.size (uint32_t)}
            }
}

hypercall! {xen_domctl_set_target, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_target},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.set_target.target (domid_t)}
            }
}

hypercall! {xen_domctl_subscribe, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_subscribe},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.subscribe.port (uint32_t)}
            }
}

hypercall! {xen_domctl_debug_op, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_debug_op},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.debug_op.op (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.debug_op.vcpu (uint32_t)}
            }
}

hypercall! {xen_domctl_access_required, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_access_required},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.access_required.access_required (uint8_t)}
            }
}

hypercall! {xen_domctl_audit_p2m, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_audit_p2m},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.audit_p2m.orphans (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.audit_p2m.m2p_bad (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.audit_p2m.p2m_bad (uint64_t)}
            }
}

hypercall! {xen_domctl_set_virq_handler, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_virq_handler},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.set_virq_handler.virq (uint32_t)}
            }
}

hypercall! {xen_domctl_gdbsx_guest_memio, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gdbsx_guestmemio},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.pgd3val (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.gva (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.uva (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.len (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.gwr (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_guest_memio.remain (uint32_t)}
            }
}

hypercall! {xen_domctl_set_broken_page_p2m, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_broken_page_p2m},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.set_broken_page_p2m.pfn (uint64_t)}
            }
}

hypercall! {xen_domctl_cacheflush, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_cacheflush},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.cacheflush.start_pfn (xen_pfn_t)},
               hypercall_struct_field!{var xen_domctl:u.cacheflush.nr_pfns (xen_pfn_t)}
            }
}

hypercall! {xen_domctl_gdbsx_pausevcpu, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gdbsx_pausevcpu},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_pauseunp_vcpu.vcpu (uint32_t)}
            }
}

hypercall! {xen_domctl_gdbsx_unpausevcpu, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gdbsx_unpausevcpu},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_pauseunp_vcpu.vcpu (uint32_t)}
            }
}

hypercall! {xen_domctl_gdbsx_domstatus, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_gdbsx_domstatus},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_domstatus.paused (uint8_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_domstatus.vcpu_id (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.gdbsx_domstatus.vcpu_ev (uint32_t)}
            }
}

hypercall! {xen_domctl_setvnumainfo, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_setvnumainfo},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vnuma.nr_vnodes (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vnuma.nr_vmemranges (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vnuma.nr_vcpus (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vnuma.vdistance (__u_int)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vnuma.vcpu_to_vnode (__u_int)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vnuma.vnode_to_pnode (__u_int)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.vnuma.vmemrange (xen_vmemrange_t)}
            }
}

hypercall! {xen_domctl_psr_cmt_op, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_psr_cmt_op},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.psr_cmt_op.cmd (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.psr_cmt_op.data (uint32_t)}
            }
}

hypercall! {xen_domctl_psr_alloc, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_psr_alloc},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.psr_alloc.cmd (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.psr_alloc.target (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.psr_alloc.data (uint64_t)}
            }
}

hypercall! {xen_domctl_vuart_op, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_vuart_op},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vuart_op.cmd (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vuart_op.type_ (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vuart_op.gfn (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.vuart_op.console_domid (domid_t)},
               hypercall_struct_field!{var xen_domctl:u.vuart_op.evtchn (evtchn_port_t)}
            }
}

hypercall! {xen_domctl_vmtrace_op, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_vmtrace_op},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.vmtrace_op.cmd (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vmtrace_op.vcpu (uint32_t)},
               hypercall_struct_field!{var xen_domctl:u.vmtrace_op.key (uint64_t)},
               hypercall_struct_field!{var xen_domctl:u.vmtrace_op.value (uint64_t)}
            }
}

hypercall! {xen_domctl_get_paging_mempool_size, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_get_paging_mempool_size},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.paging_mempool.size (uint64_t)}
            }
}

hypercall! {xen_domctl_set_paging_mempool_size, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_paging_mempool_size},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.paging_mempool.size (uint64_t)}
            }
}

hypercall! {xen_domctl_dt_overlay, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_dt_overlay},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{buf_with_size xen_domctl:u.dt_overlay.overlay_fdt => u.dt_overlay.overlay_fdt_size},
               hypercall_struct_field!{var xen_domctl:u.dt_overlay.overlay_op (uint8_t)}
            }
}

hypercall! {xen_domctl_set_llc_colors, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_set_llc_colors},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.set_llc_colors.num_llc_colors (uint32_t)},
               hypercall_struct_field!{typed_buf_wo_size xen_domctl:u.set_llc_colors.llc_colors (u32)}
            }
}

hypercall! {xen_domctl_get_domain_state, __HYPERVISOR_domctl,
            hypercall_arg!{0, complex_struct xen_domctl,
               hypercall_struct_field!{const xen_domctl:cmd (uint32_t) = XEN_DOMCTL_get_domain_state},
               hypercall_struct_field!{const xen_domctl:interface_version (uint32_t) = XEN_DOMCTL_INTERFACE_VERSION},
               hypercall_struct_field!{var xen_domctl:u.get_domain_state.state (uint16_t)},
               hypercall_struct_field!{var xen_domctl:u.get_domain_state.caps (uint16_t)},
               hypercall_struct_field!{var xen_domctl:u.get_domain_state.unique_id (uint64_t)}
            }
}

pub fn generate_domctl_op<S>(state: &mut S) -> GenericHypercallInput
where
    S: HasRand + HasMaxSize,
{
    // Safety: CTRS are nonempty
    GenericHypercallInput::new(state.rand_mut().choose(CTRS).unwrap()(), state)
}
